periphemu.remove("chest_0")
periphemu.remove("chest_1")
periphemu.remove("chest_2")
periphemu.remove("chest_3")
periphemu.remove("chest_4")
periphemu.remove("chest_5")
periphemu.remove("right")
periphemu.create("chest_0", "chest")
periphemu.create("chest_1", "chest")
periphemu.create("chest_2", "chest")
periphemu.create("chest_3", "chest")
periphemu.create("chest_4", "chest")
periphemu.create("chest_5", "chest")
periphemu.create("right", "chest")
local chest = peripheral.wrap("chest_0")
chest.setItem(1, { name = "iron_ingot", count = 64 })
chest.setItem(2, { name = "iron_ingot", count = 64 })
chest.setItem(3, { name = "iron_ingot", count = 64 })
local chest = peripheral.wrap("chest_1")
chest.setItem(1, { name = "iron_ingot", count = 64 })
local chest = peripheral.wrap("chest_5")
chest.setItem(1, { name = "steak", count = 10 })